export { default as Home } from "./Home";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Account } from "./Account";
export { default as Forum } from "./Forum";
export { default as Issues } from "../pages/forum/Issues";
export { default as Issue } from "../pages/forum/Issue";
export { default as TanamPohon } from "./TanamPohon";
export { default as Leaderboard } from "./Leaderboard";
