export { default as Home } from "./Home";
export { default as SignUp } from "./SignUp";
export { default as Login } from "./Login";
export { default as Account } from "./Account";
export { default as EditProfile } from "./account/EditProfile"
export { default as ContactUs } from "./account/contactUs"
export { default as Forum } from "./Forum";
export { default as TanamPohon } from "./TanamPohon";
export { default as Leaderboard } from "./Leaderboard";
